extern const bcstring be_const_str_;
extern const bcstring be_const_str_Hello;
extern const bcstring be_const_str__X2Etest_var;
extern const bcstring be_const_str_as;
extern const bcstring be_const_str_break;
extern const bcstring be_const_str_bytes;
extern const bcstring be_const_str_class;
extern const bcstring be_const_str_continue;
extern const bcstring be_const_str_def;
extern const bcstring be_const_str_do;
extern const bcstring be_const_str_elif;
extern const bcstring be_const_str_else;
extern const bcstring be_const_str_end;
extern const bcstring be_const_str_except;
extern const bcstring be_const_str_false;
extern const bcstring be_const_str_for;
extern const bcstring be_const_str_if;
extern const bcstring be_const_str_import;
extern const bcstring be_const_str_init;
extern const bcstring be_const_str_nil;
extern const bcstring be_const_str_raise;
extern const bcstring be_const_str_return;
extern const bcstring be_const_str_static;
extern const bcstring be_const_str_true;
extern const bcstring be_const_str_try;
extern const bcstring be_const_str_var;
extern const bcstring be_const_str_while;

/* weak strings */
