#include "be_constobj.h"

static be_define_const_map_slots(Berry_Style_Class_map) {
    { be_const_key(Set_Shadow_Width, -1), be_const_ctype_func(Berry_Style_Class_Set_Shadow_Width_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Transition, -1), be_const_ctype_func(Berry_Style_Class_Set_Transition_void_Graphics_TypesStyle_ClassTransition_Descriptor_Type) },
    { be_const_key(Set_Arc_Opacity, 0), be_const_ctype_func(Berry_Style_Class_Set_Arc_Opacity_void_Graphics_TypesOpacity_Type) },
    { be_const_key(Set_Image_Recolor_Opacity, 46), be_const_ctype_func(Berry_Style_Class_Set_Image_Recolor_Opacity_void_Graphics_TypesOpacity_Type) },
    { be_const_key(Set_Flex_Flow, -1), be_const_ctype_func(Berry_Style_Class_Set_Flex_Flow_void_Graphics_TypesFlex_Flow_Type) },
    { be_const_key(Set_Background_Gradient, 82), be_const_ctype_func(Berry_Style_Class_Set_Background_Gradient_void_Types_ClassGradientDescriptor_Type) },
    { be_const_key(Set_Height, 23), be_const_ctype_func(Berry_Style_Class_Set_Height_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Background_Image_Recolor_Opacity, -1), be_const_ctype_func(Berry_Style_Class_Set_Background_Image_Recolor_Opacity_void_Graphics_TypesOpacity_Type) },
    { be_const_key(Reset, -1), be_const_ctype_func(Berry_Style_Class_Reset_void) },
    { be_const_key(Set_Background_Color, -1), be_const_ctype_func(Berry_Style_Class_Set_Background_Color_void_Graphics_TypesStyle_ClassColor_Type) },
    { be_const_key(Set_Border_Side, 21), be_const_ctype_func(Berry_Style_Class_Set_Border_Side_void_Graphics_TypesBorder_Side_Type) },
    { be_const_key(Set_Border_Opacity, 24), be_const_ctype_func(Berry_Style_Class_Set_Border_Opacity_void_Graphics_TypesOpacity_Type) },
    { be_const_key(Set_Grid_Cell_X__Alignment, -1), be_const_ctype_func(Berry_Style_Class_Set_Grid_Cell_X_Alignment_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Transform_Height, -1), be_const_ctype_func(Berry_Style_Class_Set_Transform_Height_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Outline_Pad, -1), be_const_ctype_func(Berry_Style_Class_Set_Outline_Pad_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Get_Pointer, -1), be_const_ctype_func(Berry_Style_Class_Get_Pointer_void) },
    { be_const_key(Set_Grid_Cell_Column_Span, 77), be_const_ctype_func(Berry_Style_Class_Set_Grid_Cell_Column_Span_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Blend_Mode, 69), be_const_ctype_func(Berry_Style_Class_Set_Blend_Mode_void_Types_ClassBlendMode_Type) },
    { be_const_key(Set_Clip_Corner, -1), be_const_ctype_func(Berry_Style_Class_Set_Clip_Corner_void_bool) },
    { be_const_key(Set_Grid_Column_Alignment, 103), be_const_ctype_func(Berry_Style_Class_Set_Grid_Column_Alignment_void_Graphics_TypesGrid_Alignment_Type) },
    { be_const_key(Set_Text_Line_Space, -1), be_const_ctype_func(Berry_Style_Class_Set_Text_Line_Space_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Transform_Angle, -1), be_const_ctype_func(Berry_Style_Class_Set_Transform_Angle_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Text_Opacity, 66), be_const_ctype_func(Berry_Style_Class_Set_Text_Opacity_void_Graphics_TypesOpacity_Type) },
    { be_const_key(Set_Background_Gradient_Direction, -1), be_const_ctype_func(Berry_Style_Class_Set_Background_Gradient_Direction_void_Types_ClassGradientDirection_Type) },
    { be_const_key(Set_Pad_Vertical, -1), be_const_ctype_func(Berry_Style_Class_Set_Pad_Vertical_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Outline_Opacity, 68), be_const_ctype_func(Berry_Style_Class_Set_Outline_Opacity_void_Graphics_TypesOpacity_Type) },
    { be_const_key(Set_Line_Rounded, 67), be_const_ctype_func(Berry_Style_Class_Set_Line_Rounded_void_bool) },
    { be_const_key(Set_Pad_Column, -1), be_const_ctype_func(Berry_Style_Class_Set_Pad_Column_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Grid_Row_Descriptor_Array, -1), be_const_ctype_func(Berry_Style_Class_Set_Grid_Row_Descriptor_Array_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Grid_Cell_Row_Span, 53), be_const_ctype_func(Berry_Style_Class_Set_Grid_Cell_Row_Span_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Size, 15), be_const_ctype_func(Berry_Style_Class_Set_Size_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Background_Image_Source, -1), be_const_ctype_func(Berry_Style_Class_Set_Background_Image_Source_void_void) },
    { be_const_key(Set_Border_Width, -1), be_const_ctype_func(Berry_Style_Class_Set_Border_Width_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Maximum_Height, -1), be_const_ctype_func(Berry_Style_Class_Set_Maximum_Height_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Line_Width, -1), be_const_ctype_func(Berry_Style_Class_Set_Line_Width_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Grid_Column_Descriptor_Array, -1), be_const_ctype_func(Berry_Style_Class_Set_Grid_Column_Descriptor_Array_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Grid_Row_Alignment, -1), be_const_ctype_func(Berry_Style_Class_Set_Grid_Row_Alignment_void_Graphics_TypesGrid_Alignment_Type) },
    { be_const_key(deinit, -1), be_const_ctype_func(Berry_Style_Class_Deinitialize_void) },
    { be_const_key(Set_Shadow_Spread, -1), be_const_ctype_func(Berry_Style_Class_Set_Shadow_Spread_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_X_, 1), be_const_ctype_func(Berry_Style_Class_Set_X_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Flex_Cross_Place, 6), be_const_ctype_func(Berry_Style_Class_Set_Flex_Cross_Place_void_Graphics_TypesFlex_Alignment_Type) },
    { be_const_key(Set_Pad_Right, -1), be_const_ctype_func(Berry_Style_Class_Set_Pad_Right_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Border_Post, -1), be_const_ctype_func(Berry_Style_Class_Set_Border_Post_void_bool) },
    { be_const_key(Set_Animation_Time, -1), be_const_ctype_func(Berry_Style_Class_Set_Animation_Time_void_uint32_t) },
    { be_const_key(Set_Minimum_Height, 3), be_const_ctype_func(Berry_Style_Class_Set_Minimum_Height_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Line_Color, -1), be_const_ctype_func(Berry_Style_Class_Set_Line_Color_void_Graphics_TypesStyle_ClassColor_Type) },
    { be_const_key(Set_Base_Direction, -1), be_const_ctype_func(Berry_Style_Class_Set_Base_Direction_void_Types_ClassBase_DirectionType) },
    { be_const_key(Set_Grid_Cell_Y_Alignment, -1), be_const_ctype_func(Berry_Style_Class_Set_Grid_Cell_Y_Alignment_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Text_Font, -1), be_const_ctype_func(Berry_Style_Class_Set_Text_Font_void_Types_ClassFont_Type) },
    { be_const_key(Initialize, 75), be_const_ctype_func(Berry_Style_Class_Initialize_void) },
    { be_const_key(Set_Arc_Image_Source, -1), be_const_ctype_func(Berry_Style_Class_Set_Arc_Image_Source_void_void) },
    { be_const_key(Set_Y, -1), be_const_ctype_func(Berry_Style_Class_Set_Y_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Pad_Horizontal, 76), be_const_ctype_func(Berry_Style_Class_Set_Pad_Horizontal_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Alignment, 104), be_const_ctype_func(Berry_Style_Class_Set_Alignment_void_Graphics_TypesAlignment_Type) },
    { be_const_key(Set_Background_Main_Stop, -1), be_const_ctype_func(Berry_Style_Class_Set_Background_Main_Stop_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Remove_Property, -1), be_const_ctype_func(Berry_Style_Class_Remove_Property_void_Graphics_TypesStyle_ClassProperty_Type) },
    { be_const_key(Register_Property, -1), be_const_ctype_func(Berry_Style_Class_Register_Property_void_uint8_t) },
    { be_const_key(Set_Maximum_Width, -1), be_const_ctype_func(Berry_Style_Class_Set_Maximum_Width_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Outline_Width, -1), be_const_ctype_func(Berry_Style_Class_Set_Outline_Width_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(init, -1), be_const_ctype_func(Berry_Style_Class_Initialize_Graphics_TypesStyle_Class) },
    { be_const_key(Set_Translate_Y, 87), be_const_ctype_func(Berry_Style_Class_Set_Translate_Y_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Transform_Zoom, 101), be_const_ctype_func(Berry_Style_Class_Set_Transform_Zoom_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Shadow_Offset_X_, -1), be_const_ctype_func(Berry_Style_Class_Set_Shadow_Offset_X_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Pad_Bottom, -1), be_const_ctype_func(Berry_Style_Class_Set_Pad_Bottom_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(_p, 49), be_const_var(0) },
    { be_const_key(Set_Shadow_Offset_Y, 91), be_const_ctype_func(Berry_Style_Class_Set_Shadow_Offset_Y_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Shadow_Opacity, -1), be_const_ctype_func(Berry_Style_Class_Set_Shadow_Opacity_void_Graphics_TypesOpacity_Type) },
    { be_const_key(Set_Layout, 102), be_const_ctype_func(Berry_Style_Class_Set_Layout_void_uint16_t) },
    { be_const_key(Set_Pad_All, 105), be_const_ctype_func(Berry_Style_Class_Set_Pad_All_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Color_Filter_Opacity, -1), be_const_ctype_func(Berry_Style_Class_Set_Color_Filter_Opacity_void_Graphics_TypesOpacity_Type) },
    { be_const_key(Set_Line_Dash_Width, -1), be_const_ctype_func(Berry_Style_Class_Set_Line_Dash_Width_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Color_Filter_Descriptor, 25), be_const_ctype_func(Berry_Style_Class_Set_Color_Filter_Descriptor_void_Graphics_TypesStyle_ClassColor_Filter_Descriptor_Type) },
    { be_const_key(Set_Image_Opacity, 61), be_const_ctype_func(Berry_Style_Class_Set_Image_Opacity_void_Graphics_TypesOpacity_Type) },
    { be_const_key(Set_Pad_Row, 31), be_const_ctype_func(Berry_Style_Class_Set_Pad_Row_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Background_Dither_Mode, 60), be_const_ctype_func(Berry_Style_Class_Set_Background_Dither_Mode_void_Types_ClassDither_ModeType) },
    { be_const_key(Set_Outline_Color, -1), be_const_ctype_func(Berry_Style_Class_Set_Outline_Color_void_Graphics_TypesStyle_ClassColor_Type) },
    { be_const_key(Set_Text_Alignment, 89), be_const_ctype_func(Berry_Style_Class_Set_Text_Alignment_void_Graphics_TypesText_Alignment_Type) },
    { be_const_key(Set_Background_Image_Opacity, 47), be_const_ctype_func(Berry_Style_Class_Set_Background_Image_Opacity_void_Graphics_TypesOpacity_Type) },
    { be_const_key(Set_Radius, 52), be_const_ctype_func(Berry_Style_Class_Set_Radius_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Line_Dash_Gap, -1), be_const_ctype_func(Berry_Style_Class_Set_Line_Dash_Gap_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Minimum_Width, 18), be_const_ctype_func(Berry_Style_Class_Set_Minimum_Width_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Text_Color, -1), be_const_ctype_func(Berry_Style_Class_Set_Text_Color_void_Graphics_TypesStyle_ClassColor_Type) },
    { be_const_key(Set_Flex_Track_Place, -1), be_const_ctype_func(Berry_Style_Class_Set_Flex_Track_Place_void_Graphics_TypesFlex_Alignment_Type) },
    { be_const_key(Set_Arc_Width, -1), be_const_ctype_func(Berry_Style_Class_Set_Arc_Width_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Opacity, -1), be_const_ctype_func(Berry_Style_Class_Set_Opacity_void_Graphics_TypesOpacity_Type) },
    { be_const_key(Set_Width, 65), be_const_ctype_func(Berry_Style_Class_Set_Width_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Translate_X_, -1), be_const_ctype_func(Berry_Style_Class_Set_Translate_X_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Background_Gradient_Stop, 45), be_const_ctype_func(Berry_Style_Class_Set_Background_Gradient_Stop_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Flex_Main_Place, -1), be_const_ctype_func(Berry_Style_Class_Set_Flex_Main_Place_void_Graphics_TypesFlex_Alignment_Type) },
    { be_const_key(Set_Grid_Cell_Column_Position, -1), be_const_ctype_func(Berry_Style_Class_Set_Grid_Cell_Column_Position_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Background_Image_Tiled, -1), be_const_ctype_func(Berry_Style_Class_Set_Background_Image_Tiled_void_bool) },
    { be_const_key(Set_Background_Gradient_Color, -1), be_const_ctype_func(Berry_Style_Class_Set_Background_Gradient_Color_void_Graphics_TypesStyle_ClassColor_Type) },
    { be_const_key(Set_Transform_Width, -1), be_const_ctype_func(Berry_Style_Class_Set_Transform_Width_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Arc_Color, -1), be_const_ctype_func(Berry_Style_Class_Set_Arc_Color_void_Graphics_TypesStyle_ClassColor_Type) },
    { be_const_key(Set_Shadow_Color, -1), be_const_ctype_func(Berry_Style_Class_Set_Shadow_Color_void_Graphics_TypesStyle_ClassColor_Type) },
    { be_const_key(Set_Pad_Gap, -1), be_const_ctype_func(Berry_Style_Class_Set_Pad_Gap_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Background_Opacity, -1), be_const_ctype_func(Berry_Style_Class_Set_Background_Opacity_void_Graphics_TypesOpacity_Type) },
    { be_const_key(Set_Background_Image_Recolor, 62), be_const_ctype_func(Berry_Style_Class_Set_Background_Image_Recolor_void_Graphics_TypesStyle_ClassColor_Type) },
    { be_const_key(Set_Line_Opacity, -1), be_const_ctype_func(Berry_Style_Class_Set_Line_Opacity_void_Graphics_TypesOpacity_Type) },
    { be_const_key(Set_Animation_Speed, -1), be_const_ctype_func(Berry_Style_Class_Set_Animation_Speed_void_uint32_t) },
    { be_const_key(Set_Arc_Rounded, 7), be_const_ctype_func(Berry_Style_Class_Set_Arc_Rounded_void_bool) },
    { be_const_key(Set_Text_Letter_Space, -1), be_const_ctype_func(Berry_Style_Class_Set_Text_Letter_Space_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Image_Recolor, -1), be_const_ctype_func(Berry_Style_Class_Set_Image_Recolor_void_Graphics_TypesStyle_ClassColor_Type) },
    { be_const_key(Set_Pad_Left, -1), be_const_ctype_func(Berry_Style_Class_Set_Pad_Left_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Grid_Cell_Row_Position, -1), be_const_ctype_func(Berry_Style_Class_Set_Grid_Cell_Row_Position_void_Graphics_TypesCoordinate_Type) },
    { be_const_key(Set_Flex_Grow, -1), be_const_ctype_func(Berry_Style_Class_Set_Flex_Grow_void_uint8_t) },
    { be_const_key(Set_Text_Decor, -1), be_const_ctype_func(Berry_Style_Class_Set_Text_Decor_void_Types_ClassTextDecor_Type) },
    { be_const_key(Set_Border_Color, -1), be_const_ctype_func(Berry_Style_Class_Set_Border_Color_void_Graphics_TypesStyle_ClassColor_Type) },
    { be_const_key(Set_Pad_Top, 32), be_const_ctype_func(Berry_Style_Class_Set_Pad_Top_void_Graphics_TypesCoordinate_Type) },
};

static be_define_const_map(
    Berry_Style_Class_map,
    109
);

BE_EXPORT_VARIABLE be_define_const_class(
    Berry_Style_Class,
    1,
    NULL,
    Style_Type
);
