// This file is automatically generated by the Generate.py script.
#include "Software/Berry/Berry.hpp"
extern "C"
{
#include "be_constobj.h"
#include "be_mapping.h"
}
using namespace Xila_Namespace;

void* Berry_Instruction_Class_Initialize(Module_Class* Sender = NULL, Module_Class* Receiver = NULL)
{
    if ((Sender == NULL) && (Receiver == NULL))
        return new Instruction_Class();
    else
        return new Instruction_Class(Sender, Receiver);
}
BE_FUNC_CTYPE_DECLARE(Berry_Instruction_Class_Initialize, "+_p", "..");

void Berry_Instruction_Class_Deinitialize(Instruction_Class* Instruction)
{
    delete Instruction;
}
BE_FUNC_CTYPE_DECLARE(Berry_Instruction_Class_Deinitialize, "", ".");

void Berry_Instruction_Class_Set_Sender(Instruction_Class* Instruction, Module_Class* Sender)
{
    Instruction->Set_Sender(Sender);
}
BE_FUNC_CTYPE_DECLARE(Berry_Instruction_Class_Set_Sender, "", "..");

void Berry_Instruction_Class_Set_Receiver(Instruction_Class* Instruction, Module_Class* Receiver)
{
    Instruction->Set_Receiver(Receiver);
}
BE_FUNC_CTYPE_DECLARE(Berry_Instruction_Class_Set_Receiver, "", "..");

Module_Class* Berry_Instruction_Class_Get_Sender(Instruction_Class* Instruction)
{
    return Instruction->Get_Sender();
}
BE_FUNC_CTYPE_DECLARE(Berry_Instruction_Class_Get_Sender, "Module_Class", ".");

Module_Class* Berry_Instruction_Class_Get_Receiver(Instruction_Class* Instruction)
{
    return Instruction->Get_Receiver();
}
BE_FUNC_CTYPE_DECLARE(Berry_Instruction_Class_Get_Receiver, "Module_Class", ".");



/*
class Berry_Instruction_Type(scope:global, name:Instruction_Type)
{
    _p, var
    init, ctype_func(Berry_Instruction_Class_Initialize)
    deinit, ctype_func(Berry_Instruction_Class_Deinitialize)
    Set_Sender, ctype_func(Berry_Instruction_Class_Set_Sender)
    Set_Receiver, ctype_func(Berry_Instruction_Class_Set_Receiver)
    Get_Sender, ctype_func(Berry_Instruction_Class_Get_Sender)
    Get_Receiver, ctype_func(Berry_Instruction_Class_Get_Receiver)

}
*/

